### ISSUE TITLE
Build weight logging api

### ISSUE THREAD

**Issue by LucasClarkson** [Meal-Planning/nutrition-service#4]
We need an api for logging a user's weight and body measurements. This should probably wait on the user api to be completed.

**Comment by LucasClarkson** [comment]
@cduzan What functions can you think of for this? Right now, you can log your current weight and it sets it as your current weight and also logs it to your history of weights. I think we'll at least need a way to pull back the history for a certain timespan and also get the current weight.

**Comment by cduzan** [comment]
Yea, sounds about right. Should we have a way to log a weight in the past?

**Comment by LucasClarkson** [comment]
I don't think so. I've never seen that feature on any fitness/tracking app.

**Comment by LucasClarkson** [comment]
Current weight is stored on the user, so I can't think of a real reason why you would need to get it separately from the user. Leaving that route out for now.
